### ISSUE TITLE
Package can not be added to .Net Core 2.0 class library

### ISSUE THREAD

**Issue by gfgw** [Horusiath/Akka.Serialization.Bond#3]
When I try to add Akka.Serialization.Bond to a .Net Core 2.0 class library, I get the following error message:

> Package restore failed. Rolling back package changes for 'AkkaMSBond'.

The package is not added to the project.

Steps to reproduce (using Visual Studio 2017):

1. Create a new project, .Net Core 2.0 class library
2. Add the following packages:
- Akka
- Akka.Persistence
- Bond.Core.CSharp (and optionally Bond.Runtime.CSharp and/or Bond.CSharp)
3. Add the package Akka.Serialization.Bond.

The error also occurs when only Akka and Akka.Persistance are added. Further test showed the error also occurred on a .Net Standard class library.

**Comment by Horusiath** [comment]
I first need to verify this issue. If it turns out to be the case, I'll try to release new nuget package later on today.

**Comment by Horusiath** [comment]
Akka.Serialization.Bond v0.2. has been just published (see: https://www.nuget.org/packages/Akka.Serialization.Bond/0.2.0) - it targets .net standard 1.6 and .net full framework 4.6.2. If any problems will arise, feel free to reopen this issue.
